'use client';
import {useEffect,useRef,useState} from 'react';
export function dialogueWords(text:string){const lines=Array.from(text.matchAll(/[“"]([^”"]+)[”"]/g),m=>m[1]);return (lines.length?lines.join(' '):text).trim().slice(0,1800);}
export function useDialogueVoice({enabled,active,id,text,speaker,replay,apiKey,onError}:{enabled:boolean;active:boolean;id:string;text:string;speaker:string;replay:number;apiKey:string;onError:(message:string)=>void}){
 const [status,setStatus]=useState<'idle'|'loading'|'speaking'>('idle');const done=useRef(''),cache=useRef(new Map<string,Blob>()),errorRef=useRef(onError);errorRef.current=onError;
 useEffect(()=>{setStatus('idle');const words=dialogueWords(text),cacheKey=`${speaker}:${words}`,playKey=`${id}:${cacheKey}:${replay}`;if(!enabled||!active||!id||!words||done.current===playKey)return;let cancelled=false,audio:HTMLAudioElement|null=null,url='';const controller=new AbortController();
 const run=async()=>{setStatus('loading');try{let blob=cache.current.get(cacheKey);if(!blob){const response=await fetch('/api/voice',{method:'POST',headers:{'Content-Type':'application/json',...(apiKey?{Authorization:`Bearer ${apiKey}`}:{})},body:JSON.stringify({text:words,speaker:['Nyx Vale','Brakk','PIP-7','Lieutenant Korr','Director Veyra'].includes(speaker)?speaker:'Game master'}),signal:controller.signal});if(!response.ok){const data=await response.json() as {error?:string};throw Error(data.error||'Voice generation failed.');}blob=await response.blob();if(cancelled)return;cache.current.set(cacheKey,blob);if(cache.current.size>32)cache.current.delete(cache.current.keys().next().value!);}if(cancelled)return;url=URL.createObjectURL(blob);audio=new Audio(url);audio.volume=.9;audio.onended=()=>{if(!cancelled){done.current=playKey;setStatus('idle');}};audio.onerror=()=>{if(!cancelled){setStatus('idle');errorRef.current('The voice could not play. Use the replay button to try again.');}};try{await audio.play();if(!cancelled)setStatus('speaking');}catch{throw Error('Tap the dialogue speaker button to play this voice. Your browser paused automatic audio.');}}catch(error){if(!cancelled){setStatus('idle');errorRef.current((error as Error).message);}}};void run();
 return()=>{cancelled=true;controller.abort();audio?.pause();if(url)URL.revokeObjectURL(url);};
 },[enabled,active,id,text,speaker,replay,apiKey]);return status;
}
